#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import unittest

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../lib"))
import language

languageToIsoIdAndBack = {
    "Afrikaans":                           ("af",  "Afrikaans"          ),
    "Albanian":                            ("sq",  "Albanian"           ),
    "American English":                    ("en",  "English"            ),
    "Amharic":                             ("am",  "Amharic"            ),
    "ancient Greek":                       ("grc", "Ancient Greek"      ),
    "Arabic":                              ("ar",  "Arabic"             ),
    "Aragonese":                           ("an",  "Aragonese"          ),
    "Aramaic":                             ("arc", "Aramaic"            ),
    "Armenian":                            ("hy",  "Armenian"           ),
    "Assamese":                            ("as",  "Assamese"           ),
    "Australian English":                  ("en",  "English"            ),
    "Austrian German":                     ("de",  "German"             ),
    "Awadhi language":                     ("awa", "Awadhi"             ),
    "Azerbaijani":                         ("az",  "Azerbaijani"        ),
    "Bahasa Melayu Sabah":                 ("ms",  "Malay"              ),
    "Basque":                              ("eu",  "Basque"             ),
    "Belarusian":                          ("be",  "Belarusian"         ),
    "Bengali":                             ("bn",  "Bengali"            ),
    u"Bokm\u00e5l":                        ("nb",  "Norwegian Bokmål"   ),
    "Bosnian":                             ("bs",  "Bosnian"            ),
    "Brazil":                              ("pt",  "Portuguese"         ),
    "Brazilian Portuguese":                ("pt",  "Portuguese"         ),
    "Breton":                              ("br",  "Breton"             ),
    "British English":                     ("en",  "English"            ),
    "Bulgarian":                           ("bg",  "Bulgarian"          ),
    "Burgundian language":                 ("de",  "German"             ),
    "Burmese":                             ("my",  "Burmese"            ),
    "Canadian English":                    ("en",  "English"            ),
    "Catalan":                             ("ca",  "Catalan"            ),
    u"Catal\u00e1n":                       ("ca",  "Catalan"            ),
    "Chinese":                             ("zh",  "Chinese"            ),
    "Church Slavonic":                     ("cu",  "Old Church Slavonic"),
    "Classical Armenian":                  ("hy",  "Armenian"           ),
    "classical Chinese":                   ("zh",  "Chinese"            ),
    "Classical Nahuatl language":          ("nah", "Nahuatl"            ),
    "Common Brittonic":                    ("br",  "Breton"             ),
    "Croatian":                            ("hr",  "Croatian"           ),
    "Czech":                               ("cs",  "Czech"              ),
    "Danish":                              ("da",  "Danish"             ),
    "Dutch":                               ("nl",  "Dutch"              ),
    "Early Modern English":                ("en",  "English"            ),
    "Early Modern Spanish":                ("es",  "Spanish"            ),
    "Early New High German":               ("de",  "German"             ),
    "Egyptian Arabic":                     ("ar",  "Arabic"             ),
    "English":                             ("en",  "English"            ),
    "Esperanto":                           ("eo",  "Esperanto"          ),
    "Estonian":                            ("et",  "Estonian"           ),
    "Faroese":                             ("fo",  "Faroese"            ),
    "Filipino":                            ("fil", "Filipino"           ),
    "Finnish":                             ("fi",  "Finnish"            ),
    "Flemish":                             ("nl",  "Dutch"              ),
    "France":                              ("fr",  "French"             ),
    "French":                              ("fr",  "French"             ),
    "Galician":                            ("gl",  "Galician"           ),
    "Geordie dialect":                     ("en",  "English"            ),
    "Georgian":                            ("ka",  "Georgian"           ),
    "German":                              ("de",  "German"             ),
    "Greek":                               ("el",  "Greek"              ),
    "Gujarati":                            ("gu",  "Gujarati"           ),
    "Hawaiian Pidgin":                     ("haw", "Hawaiian"           ),
    "Hebrew":                              ("he",  "Hebrew"             ),
    "Hiberno-English":                     ("en",  "English"            ),
    "Hindi":                               ("hi",  "Hindi"              ),
    "Hmong language":                      ("hmn", "Hmong"              ),
    "Hopi language":                       ("azc", "Uto-Aztecan"        ),
    "Hungarian":                           ("hu",  "Hungarian"          ),
    "Icelandic":                           ("is",  "Icelandic"          ),
    "Igbo language":                       ("ig",  "Igbo"               ),
    "Indian English":                      ("en",  "English"            ),
    "Indonesian":                          ("id",  "Indonesian"         ),
    "Irish":                               ("ga",  "Irish"              ),
    "Italian":                             ("it",  "Italian"            ),
    "Italiano Moderno":                    ("it",  "Italian"            ),
    "Jamaican Patois":                     ("en",  "English"            ),
    "Japanese":                            ("ja",  "Japanese"           ),
    "Judeo-Arabic languages":              ("jrb", "Judeo-Arabic"       ),
    "Kanbun":                              ("ja",  "Japanese"           ),
    "Kannada":                             ("kn",  "Kannada"            ),
    "Karelian":                            ("krl", "Karelian"           ),
    "Kashubian language":                  ("csb", "Kashubian"          ),
    "Katharevousa":                        ("el",  "Greek"              ),
    "Kerewe language":                     ("bnt", "Bantu"              ),
    "Khmer":                               ("km",  "Central Khmer"      ),
    "Koine Greek":                         ("el",  "Greek"              ),
    "Konkani":                             ("kok", "Konkani"            ),
    "Korean":                              ("ko",  "Korean"             ),
    "Ladino":                              ("lad", "Ladino"             ),
    "Late Old Japanese":                   ("ja",  "Japanese"           ),
    "Latin":                               ("la",  "Latin"              ),
    "Lithuanian":                          ("lt",  "Lithuanian"         ),
    "Middle English":                      ("en",  "English"            ),
    "Macedonian":                          ("mk",  "Macedonian"         ),
    "Maghrebi Arabic":                     ("ar",  "Arabic"             ),
    "Maithili language":                   ("bh",  "Bihari"             ),
    "Malay":                               ("ms",  "Malay"              ),
    "Malayalam":                           ("ml",  "Malayalam"          ),
    "Malaysian":                           ("ms",  "Malay"              ),
    "Malay trade and creole languages":    ("ms",  "Malay"              ),
    "Mandarin Chinese":                    ("zh",  "Chinese"            ),
    "Manglish":                            ("en",  "English"            ),
    "Marathi":                             ("mr",  "Marathi"            ),
    "Massachusett language":               ("alg", "Algonquian"         ),
    "Medieval Latin":                      ("la",  "Latin"              ),
    "Middle English":                      ("en",  "English"            ),
    "Middle French":                       ("fr",  "French"             ),
    "mittelalterliches Aragonesisch":      ("an",  "Aragonese"          ),
    "Modern Greek":                        ("el",  "Greek"              ),
    "Mon language":                        ("km",  "Central Khmer"      ),
    "Nahuatl":                             ("nah", "Nahuatl"            ),
    "Neapolitan":                          ("nap", "Neapolitan"         ),
    "Nepali":                              ("ne",  "Nepali"             ),
    "Netherlands":                         ("nl",  "Dutch"              ),
    "Nigerian Pidgin":                     ("en",  "English"            ),
    "Norwegian":                           ("no",  "Norwegian"          ),
    "Nynorsk":                             ("nn",  "Norwegian Nynorsk"  ),
    "Occitan":                             ("oc",  "Occitan"            ),
    "Odia":                                ("hi",  "Hindi"              ),
    "Old Chinese":                         ("zh",  "Chinese"            ),
    "Old Church Slavonic":                 ("cu",  "Old Church Slavonic"),
    "Old East Slavic":                     ("cu",  "Old Church Slavonic"),
    "Old French":                          ("fr",  "French"             ),
    "Old Norse language":                  ("non", "Old Norse"          ),
    "Old Spanish language":                ("es",  "Spanish"            ),
    "Pali":                                ("pi",  "Pali"               ),
    "Persian":                             ("fa",  "Persian"            ),
    "Philippine English":                  ("en",  "English"            ),
    "Polish":                              ("pl",  "Polish"             ),
    "Portuguese":                          ("pt",  "Portuguese"         ),
    "Prakrit":                             ("pra", "Prakrit"            ),
    "Punjabi":                             ("pa",  "Punjabi"            ),
    "Quebec French":                       ("fr",  "French"             ),
    u"radical bokm\u00e5l":                ("nb",  "Norwegian Bokmål"   ),
    "Romanian":                            ("ro",  "Romanian"           ),
    "Romansh":                             ("rm",  "Romansh"            ),
    "Russian":                             ("ru",  "Russian"            ),
    "Ruthenian":                           ("cu",  "Old Church Slavonic"),
    "Sanskrit":                            ("sa",  "Sanskrit"           ),
    "Scots language":                      ("gd",  "Scottish Gaelic"    ),
    "Scottish English":                    ("en",  "English"            ),
    "Scottish Gaelic":                     ("gd",  "Scottish Gaelic"    ),
    "Serbian":                             ("sr",  "Serbian"            ),
    "Serbo-Croatian":                      ("sr",  "Serbian"            ),
    "Shan language":                       ("th",  "Thai"               ),
    "Sicilian":                            ("scn", "Sicilian"           ),
    "Sindhi":                              ("sd",  "Sindhi"             ),
    "Sinhala":                             ("si",  "Sinhala"            ),
    "Slovak":                              ("sk",  "Slovak"             ),
    "Slovene":                             ("sl",  "Slovenian"          ),
    "Spanish":                             ("es",  "Spanish"            ),
    "Spanish language in the Philippines": ("es",  "Spanish"            ),
    "Standard Chinese":                    ("zh",  "Chinese"            ),
    "Swedish":                             ("sv",  "Swedish"            ),
    "Tagalog":                             ("fil", "Filipino"           ),
    "Taglish":                             ("fil", "Filipino"           ),
    "Tamil":                               ("ta",  "Tamil"              ),
    "Telugu":                              ("te",  "Telugu"             ),
    "Thai":                                ("th",  "Thai"               ),
    "Traditional Chinese":                 ("zh",  "Chinese"            ),
    "Traditional Chinese characters":      ("zh",  "Chinese"            ),
    "Tuareg languages":                    ("ber", "Berber"             ),
    "Turkish":                             ("tr",  "Turkish"            ),
    "Ukrainian":                           ("uk",  "Ukrainian"          ),
    "Urdu":                                ("ur",  "Urdu"               ),
    "Valencian":                           ("ca",  "Catalan"            ),
    "Vietnamese":                          ("vi",  "Vietnamese"         ),
    "Welsh":                               ("cy",  "Welsh"              ),
    "Western Armenian":                    ("hy",  "Armenian"           ),
    "Written vernacular Chinese":          ("zh",  "Chinese"            ),
    "Yiddish":                             ("yi",  "Yiddish"            ),
    "Yucatec Maya":                        ("myn", "Mayan"              )
}

class TestLanguage(unittest.TestCase):
    def testLanguage(self):
        for name in languageToIsoIdAndBack:
            pair = languageToIsoIdAndBack[name]
            self.assertEqual(language.nameToIsoId(name), pair[0],
                             "Expected language %s to map to code %s, got %s" % (name, pair[0], language.nameToIsoId(name)))
            self.assertEqual(language.isoIdToName(pair[0]), pair[1])


    def testBadLanguage(self):
        error = False

        try:
            language.nameToIsoId("n/a (silent film)")
        except KeyError:
            error = True

        self.assertTrue(error, "Expected a KeyError on nameToIsoId('n/a (silent film)')")

if __name__ == '__main__':
    unittest.main()
